### ISSUE TITLE
Camera motion option is locked, no way to activate it

### ISSUE THREAD

**Issue by neodraig** [baggyg/BendyVR#1]
Hello,
In the the main settings the "camera motion" option is locked and it's impossible to activate it.
I love to use head bobbing in VR games when I get the chance as for me it really improves the feeling of walking (without it, moving feels like being on wheels or controlling a camera dolly).
Is there a workaround to force it, maybe in an ini file ?
Or could you enable it? 
It's an option so nobody has to activate it if it doesn't like it, but for the people like me who enjoy it in VR, it's a nice option to have (and yes, even in VR).

**Comment by baggyg** [comment]
I could potentially add a hidden option for headbob. This would need to be a new release though. Let me get back to you.

**Comment by neodraig** [comment]
Thanks a lot for considering it.
Just out of curiosity, why did you completely locked it ?
It's just a toggle option, that wasn't necessary. Leaving it off by default would have been enough and would have allowed people like me who enjoy head bobbing in VR to just turn it on.

**Comment by baggyg** [comment]
I had to take it out because it simply didn't work. OpenXR by default locks the camera movement completely so anything that tries to affect it causes issues. Looking into it now

**Comment by neodraig** [comment]
Oh sorry for the trouble. I really thought you had locked it because you'd thought nobody wanted it, I didn't know it was an OpenXR restriction.

**Comment by baggyg** [comment]
This is now complete. In the latest release dropping today. 

Select in Options -> Settings -> Camera Motion.

**Comment by neodraig** [comment]
This is great news, can't wait to try it.
Thank you so much.

**Comment by baggyg** [comment]
I turned it on when testing and felt pretty nauseous after a very short period. But I know that VR preferences are highly subjective and personal, so hope this works out better for you.

**Comment by neodraig** [comment]
I've completed the first level and went through the whole chapter 2 and it's just awesome, it really improves the immersion for me.
Thanks again for taking the time to activate the option, I really appreciate it.
Is there a way I can tip you to thank you ?

**Comment by baggyg** [comment]
Great! You enjoying the game is reward enough for me. 

But if you did want to support our ongoing work and new mods (and vote on what the next project will be - vote starts on Friday), you could join our Patreon for a month:

https://www.patreon.com/teambeef

No pressure to do so though, enjoy the game!

**Comment by neodraig** [comment]
Done, thanks again for your hard work.
