### ISSUE TITLE
Hands not working - In another way..

### ISSUE THREAD

**Issue by WilsonBradley** [baggyg/BendyVR#18]
@DrBeef , Hats off to you and the amazing team..
(Old time Quake 3 mod member here..)

Anyway, I was watching Berdo Benjo video and he was using his virtual hands to interact.
After installing in Steam & running latest Mod install, everything works, EXCEPT.
I have hands that look cool, but not able to grip things / select things. I have to go into Options and turn on Laser Pointer and use that instead. 

Oculus Quest 2, using Oculus PC Link Cable (best performance/habit)

**Comment by baggyg** [comment]
Hi, I think you are mistaken. Beardo wasn't using his hands to interact. Its a selection system for level props. Weapons are fully motion tracked but not level props (like switches)
