### ISSUE TITLE
Getting this to work with Bendy and the Dark Revival

### ISSUE THREAD

**Issue by uSkizzik** [baggyg/BendyVR#19]
Hi! First off, I would like to say you've done an amazing job on this mod. I had a fun time playing trough the first and second chapter even though I almost pissed my pants.
Now, as for my issue, I want to get a fork of this working on Bendy and the Dark Revival. I'm aware the games are vastly different, however I'd like to reuse parts of your code as boilerplate, which I'm aware are borrowed from the Firewatch VR mod.
I haven't been able to get this working however. The patcher for the globalgamemanagers file seems to not be working for some reason and I would greatly appreciate it if you could help me out on this.
Here are my full logs:
```
[Message:   BepInEx] BepInEx 5.4.21.0 - Bendy and the Dark Revival (11/15/2022 10:57:25 AM)
[Info   :   BepInEx] Running under Unity v2021.3.6.8233869
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BendyVRPatcher 1.0.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :   Console] Patching Bendy VR...
[Info   :   Console] installerPath D:\Downloads\BendyVRInstall - Copy\Mod\BepInEx\patchers\BendyVRPatcher\BendyVRPatcher.dll
[Info   :   Console] gameExePath E:\Steam\steamapps\common\Bendy and the Dark Revival\Bendy and the Dark Revival.exe
[Info   :   Console] Backing up 'E:\Steam\steamapps\common\Bendy and the Dark Revival\Bendy and the Dark Revival_Data/globalgamemanagers'...
[Info   :   Console] Backup already exists.
[Info   :   Console] Using classData file from path 'D:\Downloads\BendyVRInstall - Copy\Mod\BepInEx\patchers\BendyVRPatcher\classdata.tpk'
[Error  :   BepInEx] Failed to run Initializer of Patcher: System.NullReferenceException: Object reference not set to an instance of an object
  at AssetsTools.NET.Extra.AssetHelper.FindAssetClassByID (AssetsTools.NET.ClassDatabaseFile cldb, System.UInt32 id) [0x00008] in <b9ea336f811548a8880cd5c6fcb7090e>:0 
  at AssetsTools.NET.Extra.AssetsManager.GetTemplateBaseField (AssetsTools.NET.AssetsFile file, AssetsTools.NET.AssetFileInfoEx info, System.Boolean forceFromCldb) [0x00085] in <b9ea336f811548a8880cd5c6fcb7090e>:0 
  at AssetsTools.NET.Extra.AssetsManager.GetTypeInstance (AssetsTools.NET.AssetsFile file, AssetsTools.NET.AssetFileInfoEx info, System.Boolean forceFromCldb) [0x00000] in <b9ea336f811548a8880cd5c6fcb7090e>:0 
  at Patcher.PatchVR (System.String gameManagersBackupPath, System.String gameManagersPath, System.String classDataPath) [0x0005e] in <a1a4eda46b4345e5811d8361b9ff3b07>:0 
  at Patcher.Initialize () [0x00083] in <a1a4eda46b4345e5811d8361b9ff3b07>:0 
  at BepInEx.Preloader.Patching.AssemblyPatcher.InitializePatchers () [0x0001e] in <fc9d7fbc6dcb44cf87be11d8d92ae161>:0 
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   BepInEx] Patching [Assembly-CSharp] with [Patcher]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
```

**Comment by uSkizzik** [comment]
I'm also going to ping @Raicuparta on this as the patcher in this mod doesn't seem to be any different from the Firewatch one.

**Comment by Raicuparta** [comment]
The version of Unity used in that game might be too recent for that method. I don't think Unity 2021 supports the globalgamemanagers patching method for enabling VR. The alternative is patching the XR plugin at runtime, which you'll find in other repositories. I think the only public repo I have that uses that method is Hard space Shipbreaker, but there are other people who have done the same.

**Comment by uSkizzik** [comment]
Damn, that would make sense. I actually tried modifying the file manually prior to checking out the patcher and that didn't seem to do much. The version they use in that is v2021.3.6 btw.
Anyways I'll check out that repo, thanks!

**Comment by uSkizzik** [comment]
Yo @Raicuparta, quick question, what behavior should I expect when the game doesn't have any BepInEx plugins and has only the patcher applied? Should it automatically place a VR camera for me or what? At the moment SteamVR just gets stuck on "Next Up" while the game itself runs in flatscreen mode.

**Comment by baggyg** [comment]
Hi Radostin, I see Rai has helped you get passed the first hurdle. Just as a heads up Team Beef have already publicly stated we will be doing a mod for Dark Revival. I think it makes most sense as I'm very familiar with how they program their games etc. I don't want to cause a situation whereby you feel we undercutting you so I wanted to mention this upfront. I obviously can't force you to do (or not do) anything, but if you are in a learning curve it may be the case our version comes out quite a bit quicker and may be worth looking at something else. I already have the game patched and basically up and running in VR On 18 Mar 2023 06:02, Radostin Stoyanov ***@***.***> wrote:
Yo @Raicuparta, quick question, what behavior should I expect when the game doesn't have any BepInEx plugins and has only the patcher applied? Should it automatically place a VR camera for me or what? At the moment SteamVR just gets stuck on "Next Up" while the game itself runs in flatscreen mode.

**Comment by uSkizzik** [comment]
> Hi Radostin, I see Rai has helped you get passed the first hurdle. Just as a heads up Team Beef have already publicly stated we will be doing a mod for Dark Revival. I think it makes most sense as I'm very familiar with how they program their games etc. I don't want to cause a situation whereby you feel we undercutting you so I wanted to mention this upfront. I obviously can't force you to do (or not do) anything, but if you are in a learning curve it may be the case our version comes out quite a bit quicker and may be worth looking at something else. I already have the game patched and basically up and running in VR On 18 Mar 2023 06:02, Radostin Stoyanov ***@***.***> wrote:
> Yo @Raicuparta, quick question, what behavior should I expect when the game doesn't have any BepInEx plugins and has only the patcher applied? Should it automatically place a VR camera for me or what? At the moment SteamVR just gets stuck on "Next Up" while the game itself runs in flatscreen mode.
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Meh it's still worth the time to tinker around with the gam for fun. 
Btw do you have any plans for improving this mod? Specifically in relation to the axe always rendering on top of stuff like an overlay and being unable to physically interact with doors and levers.

**Comment by baggyg** [comment]
I may look into such things for the sequel. Although the original game is pretty fun, it had some boring parts so had a mixed reaction and therefore probably not worth improving beyond standard support.

For Dark Revival we're moving to OpenXR as I think this willcause less issues with compatibility. 

As said,I can't stop you working on things but obviously we can't really help if you are working on the same game. If you decide to work on something else I can provide guidance where needed. I will therefore close this thread.
