### ISSUE TITLE
can't find teambeefInstaller.exe

### ISSUE THREAD

**Issue by nslayton24** [baggyg/BendyVR#21]
I did what it said on the "how to install" page and it didn't work. I downloaded the "bendyVR" file, I extracted it, but I don't see the teambeefInstaller.exe did I miss something?

**Comment by baggyg** [comment]
Did you properly extract it?

Here's the content of the RAR file:
![image](https://github.com/baggyg/BendyVR/assets/4569081/b5378edc-d986-4dc7-a16c-96737e34ed58)

![image](https://github.com/baggyg/BendyVR/assets/4569081/04421cca-c0cd-408a-a27d-5b6ca1429154)

**Comment by nslayton24** [comment]
I downloaded WinRAR and it finally worked! thank you so much 👍
