### ISSUE TITLE
Reset all options

### ISSUE THREAD

**Issue by pitAlex** [baggyg/BendyVR#23]
Hi, 
So I have this issue where I don't know what setting my son activated in "Options" but now, no button of the controllers works. I can move the joysticks, but A or B - nothing. How do I reset this mod so it takes initial values as the first run? Uninstall, reinstall - nothing does it. The controllers are of Oculus Quest 2.

**Comment by baggyg** [comment]
You should check the Steam VR Input settings and make sure it is using the default config. 

Also make sure the window has focus and there are no errors in the other log window.

**Comment by baggyg** [comment]
Fixed in latest release
