### ISSUE TITLE
Steam Link not responding in my Quest 2

### ISSUE THREAD

**Issue by VladGC1** [baggyg/BendyVR#24]
Hello, sorry to bother you, but I have a problem with the mod. The mod work fine on pc, but in vr works fine a little bit and then the game freezes, but only in vr and steam link gives me: ''Your pc is not responding'' But the game works fine on pc without any lag in 72fps. What can I do? Do you have a solution for this? Thank You!

**Comment by baggyg** [comment]
What's your system specs?

**Comment by VladGC1** [comment]
Its a Lenovo Legion 5 laptop with ryzen 5 5600h a rtx 3050, 16gb RAM 512 GB ssd and a 5ghz router connected via cable

**Comment by baggyg** [comment]
With a Quest 2 over Steam Link? Have you tried standard Link / AirLink?

**Comment by VladGC1** [comment]
Yes a Quest 2 over Steam link, and i've Tried airlink and link

**Comment by VladGC1** [comment]
And after that any game was broken after. What ca-n be?

**Comment by baggyg** [comment]
Are you sure its not remaining in integrated graphics mode or similar? 
Does changing the graphics settings right to the minimum make any difference? 

Your specs are a little low and laptops can be fiddly to get right. I've tried Steam Link a couple of times, but didn't find it great. Link / Airlink performed much better.

**Comment by baggyg** [comment]
> And after that any game was broken after. What ca-n be?

Try restarting headset and computer and trying again. Usually that's enough to sort itself.

**Comment by VladGC1** [comment]
No its on discrete graphics and I disabled the integrated graphics and IT doesn't Have effect If I turn to the minimum. And in Airlink performed the same the headset displays a static image and on the laptop IT tuns smoothly in 72fps. I think its not from the laptop. I restarted nothing changed. Propably an factory reset settings on the headset should do the trick?

**Comment by baggyg** [comment]
Factory reset would be a very last resort. 
How does the laptop perform in other games? Bendy performance will need a little more than usual as its injecting into an older Unity version which didn't have some of the more modern optimisations. Thinks like Ambient occlusion and Depth of Field in VR really require 3070 / 3080 cards, hence why I asked if you'd turned everything off. 

Ok, I think I misunderstood, so in VR on the laptop mirror display its smooth, but in the VR headset it is frozen?

**Comment by VladGC1** [comment]
Yes, the laptop performs really good in flat games and even vr games until now, I've installed a vr ready test and on high settings with bloom and all optional settings working really good in 40-50. And Yeah display its smooth and in vr its frozen yea.

**Comment by VladGC1** [comment]
No problem, the mod its 🔥

**Comment by baggyg** [comment]
When I'm tackling Dark Revival, I expect I'll go back and convert this to OpenXR instead of OpenVR. Should perform better. Maybe worth trying again then. 2024 sometime

**Comment by VladGC1** [comment]
I will Tell You If IT worked ora not after the Quest its charged.

**Comment by VladGC1** [comment]
Its working! I just needed to delete the oculus app and done from all folders and working. Really good mod btw!

**Comment by baggyg** [comment]
Fantastic news! Enjoy
