### ISSUE TITLE
Can't Get Past the menu or press anything

### ISSUE THREAD

**Issue by DrTrayuarus99** [baggyg/BendyVR#25]
I load into the main menu but i can't do anything else, it doesn't allow me to press anything like the keybinds aren't set

**Comment by baggyg** [comment]
Make sure the window has focus. You report is very vague. I need a bit more information to be able to help. 

I.e. headset / what the log window say etc

**Comment by norwichrunner** [comment]
I have this problem too - I switched the sticks around in options and now I'm unable to start a game or get into options as a & b do not respond.  The game is focused and there are not errors.  Any idea how to fix it?

**Comment by baggyg** [comment]
You need to delete the config:

https://github.com/baggyg/BendyVR/issues/26

**Comment by baggyg** [comment]
Fixed in the latest release. You can now user the menu and pause the game even with Switch Sticks on
