### ISSUE TITLE
Buttons Not Working.

### ISSUE THREAD

**Issue by DjTheDemon08** [baggyg/BendyVR#26]
I don’t know what happened, but for some reason when i open the game and i’m in the menu, the A - B buttons won’t work, but the joysticks do. I reinstalled, uninstalled, checked the log, but nothing. Even checked the bindings and it said default but still wouldn’t work.

 any ideas on how to fix?

**Comment by DjTheDemon08** [comment]
I’ve tried E V E R Y T H I N G and it still wont frickin work. WHAT AM I DOING WRONG!?!?

(sorry about the attitude, its just rlly annoying)

**Comment by baggyg** [comment]
You figured it out? Quite a few people have reported this, but I've never got a definitive answer of what the problem is. 

Only thing I tell them is to make sure the Bendy window itself has focus. Other than that to please send across the log from the BepExIn window (that launches with the game)

**Comment by DjTheDemon08** [comment]
No i still didn’t figure it out, not sure why the message says its closed, i never clicked anything at all. 

But i think the problem is that i clicked something in settings i believe its called “Swap Hands” but there were never intended key-binds for it (at least what i saw when i checked the bindings.) So i think it made it not possible to use anymore.

The log never had problems either or no errors.

**Comment by baggyg** [comment]
You could try deleting the mod config (which includes that option) and then seeing if it works. I don't have the exact location on me at the moment but you should find it in the BepInEx folder (possibly in config)

**Comment by DjTheDemon08** [comment]
IT WORKED! Thanks alot man!
I reinstalled the bendyvrmod files again, and searched in my folders/files “BepInEx” then opened the “config” file and deleted the thing inside of it.

Finally, i just installed the bendyvrmod again and everything went back to normal and saved.

Also I appreciate your help too for helping me, thanks alot again!

**Comment by baggyg** [comment]
Great! Glad you got there and at least I know what will work for others. 

Enjoy!
