### ISSUE TITLE
Extremely Poor Performance

### ISSUE THREAD

**Issue by creepcomix** [baggyg/BendyVR#3]
Hello Team Beef. I was really looking forward to this mod to come out. I have played about an hour through it and, for no reason, my performance is unbelievably low. The maximum framerate that I got was around 49 FPS. I tried disabling all of the extra effects: Nothing. I changed the config to performance: Still nothing. I have no clue what I should do to boost my framerate. Is there anything I'm missing?

PC Specs:
Intel i7-9700k
NVIDIA GeForce RTX 2060 SUPER
32 GB RAM

**Comment by baggyg** [comment]
With those specs it _should_ be fine. Definitely make sure Depth of Field, Ambient Occlusion and Bloom are turned off. 

Next place I would check would be the Steam Resolution. Make sure this has not been set inadvertently high. What is your VR setup? (Headset / Connection / etc)

**Comment by creepcomix** [comment]
I am currently using an Oculus Rift CV1

**Comment by baggyg** [comment]
It might also be worth turning off FSR, just to eliminate that as a suspect. 

Also updating to the latest SteamVR beta channel may help.

**Comment by creepcomix** [comment]
It was the SteamVR resolution. For some reason, it was set to max.

**Comment by baggyg** [comment]
Glad that is sorted! Enjoy the game!
