### ISSUE TITLE
Error occurring when starting the game(with mod)

### ISSUE THREAD

**Issue by DispenserBap** [baggyg/BendyVR#38]
When first downloading the mod, I would get stuck at the Ink Demon jumpscare in chapter 1. I changed the version of the game to 1.5, but as soon as I opened the game, an error message would show, and the game wouldn't start. Any way to fix this yet?
![ERRORSS](https://github.com/user-attachments/assets/cc75ea19-b5ad-46d7-815c-7cf140f7a47a)

**Comment by baggyg** [comment]
Repeat of #31
