### ISSUE TITLE
In-Game Options Menu Changes Don't Apply to Game

### ISSUE THREAD

**Issue by dakodeh** [baggyg/BendyVR#5]
Playing v1.0.0 of the mod on a Valve Index. I can invoke the in-game settings menu and I can change the values therein, but they do not apply within the game itself.

**Comment by baggyg** [comment]
Hi, we've had a couple of reports of that, but only ever with a Valve Index, which is odd. Makes me wonder if there is something silly like the button on Valve Index actually reverting the changes. However could also be something like the config being readonly for some reason (depending where you have the mod extracted).

Can you editing the BendyVRInstall\Mod\BepInEx\config\org.baggyg.vrplugins.bendyvr.cfg file manually and see if the changes are maintained when you start the game? 

I've also found an issue that the BepInEx window doesn't seem to be printing BendyVR events which would help me debug. I'll looking to solve that soon. 

I'm sure we'll get this figured out.

**Comment by BrziJoe** [comment]
I have index controllers too, the menu works, but often when going back in game everything is messed up again. I tried many options, and every time something works, and something reverts back. 
It feels like when I press button to go back, that button switch last value from menu.

**Comment by baggyg** [comment]
Ok, I think this is actually an issue with the binding. Cancel and Previous are both bound to the B button, which would mean when you exist the menu it will also move the selection. 

Please put the file bindings_knuckles.json (from https://drive.google.com/file/d/1miWvJOqrasaalts6wF1-JhgHUHZrv1Jz/view?usp=sharing)  in 
BendyVRInstall\Mod\BepInEx\plugins\BendyVRAssets\Bindings

Start the game and let me know if this fixes the issue.

**Comment by BrziJoe** [comment]
I tried it fast, it was working good for 2-3 changes, sorry I do not have more time now. I will probably play it more later today.

**Comment by BrziJoe** [comment]
It is working good, @dakodeh you may try too, so baggyg can close this issue.

**Comment by dakodeh** [comment]
I used the updated Index VR bindings provided by BaggyG and it worked perfectly to fix this issue, thanks. Certainly ok by me to close!

**Comment by baggyg** [comment]
Thanks guys - I'll be rolling out V1.1 this week so glad to know I can include these bindings and mark as fixed.
